# Mall项目阿里云基础部署配置
# 第一阶段：使用ECS + RDS + Redis + OSS的基础部署方案
# 适用于已购买：ECS、RDS、VPC、RAM的用户

version: '3.8'

services:
  # Mall管理后台
  mall-admin:
    image: registry.cn-hangzhou.aliyuncs.com/mall/mall-admin:${APP_VERSION:-1.0-SNAPSHOT}
    container_name: mall-admin
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - TZ=Asia/Shanghai
      # 阿里云RDS MySQL配置
      - SPRING_DATASOURCE_URL=jdbc:mysql://${ALIYUN_RDS_HOST}:${ALIYUN_RDS_PORT:-3306}/${MYSQL_DATABASE:-mall}?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
      # 阿里云Redis配置
      - SPRING_REDIS_HOST=${ALIYUN_REDIS_HOST}
      - SPRING_REDIS_PORT=${ALIYUN_REDIS_PORT:-6379}
      - SPRING_REDIS_PASSWORD=${REDIS_PASSWORD}
      - SPRING_REDIS_DATABASE=0
      # 阿里云OSS配置
      - ALIYUN_OSS_ENDPOINT=${ALIYUN_OSS_ENDPOINT}
      - ALIYUN_OSS_ACCESS_KEY_ID=${ALIYUN_OSS_ACCESS_KEY_ID}
      - ALIYUN_OSS_ACCESS_KEY_SECRET=${ALIYUN_OSS_ACCESS_KEY_SECRET}
      - ALIYUN_OSS_BUCKET_NAME=${ALIYUN_OSS_BUCKET_NAME}
      # JVM配置
      - JAVA_OPTS=-Xms512m -Xmx1024m -XX:+UseG1GC
    ports:
      - "8080:8080"
    volumes:
      - ${DATA_PATH}/logs/mall-admin:/app/logs
      - /etc/localtime:/etc/localtime:ro
    networks:
      - mall-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 1.5G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'

  # Mall前台门户
  mall-portal:
    image: registry.cn-hangzhou.aliyuncs.com/mall/mall-portal:${APP_VERSION:-1.0-SNAPSHOT}
    container_name: mall-portal
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - TZ=Asia/Shanghai
      # 阿里云RDS MySQL配置
      - SPRING_DATASOURCE_URL=jdbc:mysql://${ALIYUN_RDS_HOST}:${ALIYUN_RDS_PORT:-3306}/${MYSQL_DATABASE:-mall}?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
      # 阿里云Redis配置
      - SPRING_REDIS_HOST=${ALIYUN_REDIS_HOST}
      - SPRING_REDIS_PORT=${ALIYUN_REDIS_PORT:-6379}
      - SPRING_REDIS_PASSWORD=${REDIS_PASSWORD}
      - SPRING_REDIS_DATABASE=1
      # 阿里云OSS配置
      - ALIYUN_OSS_ENDPOINT=${ALIYUN_OSS_ENDPOINT}
      - ALIYUN_OSS_ACCESS_KEY_ID=${ALIYUN_OSS_ACCESS_KEY_ID}
      - ALIYUN_OSS_ACCESS_KEY_SECRET=${ALIYUN_OSS_ACCESS_KEY_SECRET}
      - ALIYUN_OSS_BUCKET_NAME=${ALIYUN_OSS_BUCKET_NAME}
      # MongoDB配置（使用容器）
      - SPRING_DATA_MONGODB_HOST=mall-mongodb
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=mall
      - SPRING_DATA_MONGODB_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - SPRING_DATA_MONGODB_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      # RabbitMQ配置（使用容器）
      - SPRING_RABBITMQ_HOST=mall-rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=${RABBITMQ_DEFAULT_USER}
      - SPRING_RABBITMQ_PASSWORD=${RABBITMQ_DEFAULT_PASS}
      # JVM配置
      - JAVA_OPTS=-Xms512m -Xmx1024m -XX:+UseG1GC
    ports:
      - "8085:8080"
    volumes:
      - ${DATA_PATH}/logs/mall-portal:/app/logs
      - /etc/localtime:/etc/localtime:ro
    networks:
      - mall-network
    depends_on:
      - mall-mongodb
      - mall-rabbitmq
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 1.5G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'

  # Mall搜索服务
  mall-search:
    image: registry.cn-hangzhou.aliyuncs.com/mall/mall-search:${APP_VERSION:-1.0-SNAPSHOT}
    container_name: mall-search
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - TZ=Asia/Shanghai
      # 阿里云RDS MySQL配置
      - SPRING_DATASOURCE_URL=jdbc:mysql://${ALIYUN_RDS_HOST}:${ALIYUN_RDS_PORT:-3306}/${MYSQL_DATABASE:-mall}?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
      # Elasticsearch配置（使用容器）
      - SPRING_ELASTICSEARCH_REST_URIS=http://mall-elasticsearch:9200
      # JVM配置
      - JAVA_OPTS=-Xms512m -Xmx1024m -XX:+UseG1GC
    ports:
      - "8081:8080"
    volumes:
      - ${DATA_PATH}/logs/mall-search:/app/logs
      - /etc/localtime:/etc/localtime:ro
    networks:
      - mall-network
    depends_on:
      - mall-elasticsearch
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 1.5G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'

  # MongoDB（容器部署）
  mall-mongodb:
    image: mongo:4.4
    container_name: mall-mongodb
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME:-mall}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD:-Mall@2024}
      - TZ=Asia/Shanghai
    ports:
      - "27017:27017"
    volumes:
      - ${DATA_PATH}/mongodb/data:/data/db
      - ${DATA_PATH}/mongodb/logs:/var/log/mongodb
      - /etc/localtime:/etc/localtime:ro
    networks:
      - mall-network
    command: mongod --auth
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

  # RabbitMQ（容器部署）
  mall-rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: mall-rabbitmq
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER:-mall}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS:-Mall@2024}
      - TZ=Asia/Shanghai
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ${DATA_PATH}/rabbitmq/data:/var/lib/rabbitmq
      - ${DATA_PATH}/rabbitmq/logs:/var/log/rabbitmq
      - /etc/localtime:/etc/localtime:ro
    networks:
      - mall-network
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

  # Elasticsearch（容器部署）
  mall-elasticsearch:
    image: elasticsearch:7.17.3
    container_name: mall-elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - TZ=Asia/Shanghai
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ${DATA_PATH}/elasticsearch/data:/usr/share/elasticsearch/data
      - ${DATA_PATH}/elasticsearch/logs:/usr/share/elasticsearch/logs
      - /etc/localtime:/etc/localtime:ro
    networks:
      - mall-network
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'

  # Nginx反向代理
  mall-nginx:
    image: mall/mall-nginx:${APP_VERSION:-1.0-SNAPSHOT}
    container_name: mall-nginx
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf/conf.d:/etc/nginx/conf.d:ro
      - ${DATA_PATH}/nginx/logs:/var/log/nginx
      - ${DATA_PATH}/ssl:/etc/nginx/ssl:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - mall-network
    depends_on:
      - mall-admin
      - mall-portal
      - mall-search
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 64M
          cpus: '0.1'

networks:
  mall-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  elasticsearch-data:
  mongodb-data:
  rabbitmq-data: