version: '3.8'

services:
  # Nginx反向代理
  nginx:
    image: nginx:1.22-alpine
    container_name: mall-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/html:/usr/share/nginx/html:ro
      - ${LOG_PATH}/nginx:/var/log/nginx
      - /etc/localtime:/etc/localtime:ro
    networks:
      - mall-network
    depends_on:
      - mall-admin
      - mall-portal
      - mall-search
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

networks:
  mall-network:
    external: true