version: '3.8'

services:
  # 后台管理系统
  mall-admin:
    image: mall/mall-admin:1.0-SNAPSHOT
    container_name: mall-admin
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - TZ=${TZ}
      - JAVA_OPTS=${JAVA_OPTS}
    ports:
      - "8080:8080"
    volumes:
      - ${LOG_PATH}/mall-admin:/var/logs
      - /etc/localtime:/etc/localtime:ro
    networks:
      - mall-network
    depends_on:
      - mysql
      - redis
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  # 前台商城系统
  mall-portal:
    image: mall/mall-portal:1.0-SNAPSHOT
    container_name: mall-portal
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - TZ=${TZ}
      - JAVA_OPTS=${JAVA_OPTS}
    ports:
      - "8085:8085"
    volumes:
      - ${LOG_PATH}/mall-portal:/var/logs
      - /etc/localtime:/etc/localtime:ro
    networks:
      - mall-network
    depends_on:
      - mysql
      - redis
      - mongodb
      - rabbitmq
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8085/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  # 商品搜索系统
  mall-search:
    image: mall/mall-search:1.0-SNAPSHOT
    container_name: mall-search
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - TZ=${TZ}
      - JAVA_OPTS=${JAVA_OPTS}
    ports:
      - "8081:8081"
    volumes:
      - ${LOG_PATH}/mall-search:/var/logs
      - /etc/localtime:/etc/localtime:ro
    networks:
      - mall-network
    depends_on:
      - mysql
      - elasticsearch
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8081/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

networks:
  mall-network:
    external: true